# Placeholder hardware configuration.
#
# This file is generated by `nixos-generate-config` on the first boot of
# real hardware (or assembled by `nixos-anywhere` from a kexec'd installer).
# Until the host physically exists, this stub keeps the flake evaluable.
#
# PR #2 (the hardware-bind PR) will replace this entire file with the
# real output, including:
#   - boot.initrd.availableKernelModules
#   - boot.initrd.kernelModules
#   - boot.kernelModules
#   - boot.extraModulePackages
#   - hardware.cpu.<vendor>.updateMicrocode
#   - nixpkgs.hostPlatform
#
# Anything not listed here defaults to safe NixOS defaults so the
# scaffold can `nix eval` end-to-end.
{ lib, ... }:
{
  # The flake fixes system to x86_64-linux; mirror that here so the
  # module evaluates standalone in tests.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Bare boot stanza — replaced wholesale in PR #2.
  boot.loader.systemd-boot.enable = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = lib.mkDefault true;
}
